/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardHomeRouteImport } from './routes/dashboard.home'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAvailabilityRouteImport } from './routes/dashboard.availability'
import { Route as BookingSlugRouteImport } from './routes/booking.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as ApiPublicGenerateBrandingRouteImport } from './routes/api/public/generate-branding'
import { Route as ApiPublicAppointmentConfirmationRouteImport } from './routes/api/public/appointment-confirmation'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DashboardRoute,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/admin/domains',
  path: '/admin/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateBrandingRoute =
  ApiPublicGenerateBrandingRouteImport.update({
    id: '/api/public/generate-branding',
    path: '/api/public/generate-branding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAppointmentConfirmationRoute =
  ApiPublicAppointmentConfirmationRouteImport.update({
    id: '/api/public/appointment-confirmation',
    path: '/api/public/appointment-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/services': typeof AdminServicesRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/api/public/appointment-confirmation': typeof ApiPublicAppointmentConfirmationRoute
  '/api/public/generate-branding': typeof ApiPublicGenerateBrandingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/services': typeof AdminServicesRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/api/public/appointment-confirmation': typeof ApiPublicAppointmentConfirmationRoute
  '/api/public/generate-branding': typeof ApiPublicGenerateBrandingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/services': typeof AdminServicesRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/api/public/appointment-confirmation': typeof ApiPublicAppointmentConfirmationRoute
  '/api/public/generate-branding': typeof ApiPublicGenerateBrandingRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/admin/domains'
    | '/admin/services'
    | '/book/$slug'
    | '/booking/$slug'
    | '/dashboard/availability'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/notifications'
    | '/dashboard/services'
    | '/dashboard/staff'
    | '/api/public/appointment-confirmation'
    | '/api/public/generate-branding'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/admin/domains'
    | '/admin/services'
    | '/book/$slug'
    | '/booking/$slug'
    | '/dashboard/availability'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/notifications'
    | '/dashboard/services'
    | '/dashboard/staff'
    | '/api/public/appointment-confirmation'
    | '/api/public/generate-branding'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/admin/domains'
    | '/admin/services'
    | '/book/$slug'
    | '/booking/$slug'
    | '/dashboard/availability'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/notifications'
    | '/dashboard/services'
    | '/dashboard/staff'
    | '/api/public/appointment-confirmation'
    | '/api/public/generate-branding'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingSlugRoute: typeof BookingSlugRoute
  ApiPublicAppointmentConfirmationRoute: typeof ApiPublicAppointmentConfirmationRoute
  ApiPublicGenerateBrandingRoute: typeof ApiPublicGenerateBrandingRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/availability': {
      id: '/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/admin/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-branding': {
      id: '/api/public/generate-branding'
      path: '/api/public/generate-branding'
      fullPath: '/api/public/generate-branding'
      preLoaderRoute: typeof ApiPublicGenerateBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointment-confirmation': {
      id: '/api/public/appointment-confirmation'
      path: '/api/public/appointment-confirmation'
      fullPath: '/api/public/appointment-confirmation'
      preLoaderRoute: typeof ApiPublicAppointmentConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardStaffRoute: DashboardStaffRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminServicesRoute: AdminServicesRoute,
  BookSlugRoute: BookSlugRoute,
  BookingSlugRoute: BookingSlugRoute,
  ApiPublicAppointmentConfirmationRoute: ApiPublicAppointmentConfirmationRoute,
  ApiPublicGenerateBrandingRoute: ApiPublicGenerateBrandingRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
